<a href="https://colab.research.google.com/github/RockNCode/2DGameEngine/blob/master/UdemyTensorFlow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)


2.8.2


In [3]:
hello = tf.constant("Hello ")
world = tf.constant("World")

type(hello)

tf.print(hello+world)

Hello World


In [4]:

a = tf.constant(10)
b = tf.constant(20)

c = a+b

tf.print(c)

30


In [5]:
tf.fill((4,4),10)


<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)>

In [7]:
tf.zeros((4,4))


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [8]:
tf.ones((4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [11]:
myrandn = tf.random.normal((4,4),mean=0.0,stddev=1.0)
myrandn


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.87608784,  2.027471  ,  0.3174134 ,  0.5940999 ],
       [-0.23505525, -1.1924014 , -0.63173926,  0.28856978],
       [-0.5849535 , -0.9482045 ,  2.5688114 ,  1.3299855 ],
       [ 0.22487809, -0.2331609 ,  1.3237414 , -0.61656827]],
      dtype=float32)>

In [12]:
myrandu = tf.random.uniform((4,4),minval=0,maxval=1)
myrandu


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.538249  , 0.642007  , 0.16044927, 0.4917338 ],
       [0.68229866, 0.8944653 , 0.6155958 , 0.56618595],
       [0.44281042, 0.81728125, 0.3742286 , 0.820917  ],
       [0.12942386, 0.8557576 , 0.51956785, 0.24322736]], dtype=float32)>